version: 2

project_name: goless

before:
  hooks:
    - go mod tidy

builds:
  - binary: goless
    env:
      - CGO_ENABLED=0
    main: ./cmd/goless
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

nfpms:
  - package_name: goless
    vendor: "Garrett D'Amore"
    homepage: https://gdamore.github.io/goless
    maintainer: garrett@damore.org
    bindir: /usr/bin
    license: "Apache 2.0"
    file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - rpm
      - deb
    description: "Modern pager"
    mtime: "{{ .CommitDate }}"
