name: macos

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: build
    runs-on: [macos-latest]

    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        go: ["stable", "oldstable"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: go.sum

      - name: Show Go version
        run: go version

      - name: Run tests
        run: go test ./...

      - name: Run tests with coverage
        run: go test -covermode=atomic -coverprofile=coverage.out ./...

      - name: Show coverage summary
        run: go tool cover -func=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          disable_search: true
          fail_ci_if_error: true
          files: coverage.out
          use_oidc: true
          verbose: true
